Repository nathachanon/EasyJob, pull requests merged in 2019-10, with the labels that each got.

#11 แก้ชื่อไฟล์ icon
  EasyJob/EasyJob.Android/EasyJob.Android.csproj
  EasyJob/EasyJob.Android/Resources/Resource.designer.cs
  EasyJob/EasyJob.Android/Resources/drawable-hdpi/check.png
  EasyJob/EasyJob.Android/Resources/drawable-hdpi/close.png
  EasyJob/EasyJob.Android/Resources/drawable-hdpi/locationArrow.png
  EasyJob/EasyJob.Android/Resources/drawable-xhdpi/check.png
  EasyJob/EasyJob.Android/Resources/drawable-xhdpi/close.png
  EasyJob/EasyJob.Android/Resources/drawable-xhdpi/locationArrow.png
  EasyJob/EasyJob.Android/Resources/drawable-xxhdpi/check.png
  EasyJob/EasyJob.Android/Resources/drawable-xxhdpi/close.png
  EasyJob/EasyJob.Android/Resources/drawable-xxhdpi/locationArrow.png
  EasyJob/EasyJob.Android/Resources/drawable-xxxhdpi/check.png
  EasyJob/EasyJob.Android/Resources/drawable-xxxhdpi/close.png
  EasyJob/EasyJob.Android/Resources/drawable-xxxhdpi/locationArrow.png
  EasyJob/EasyJob.Android/Resources/drawable/check.png
  EasyJob/EasyJob.Android/Resources/drawable/close.png
  EasyJob/EasyJob.Android/Resources/drawable/locationArrow.png
Labels: help wanted

#12 สร้าง View หน้างาน #6
  EasyJob/EasyJob/MenuBar.xaml
  EasyJob/EasyJob/Work.xaml
  EasyJob/EasyJob/Work.xaml.cs
Labels: enhancement, good first issue

#13 End #4
  EasyJob/EasyJob/MainPage.xaml
  EasyJob/EasyJob/SearchPage.xaml
  EasyJob/EasyJob/SearchPage.xaml.cs
Labels: documentation, good first issue
